# Example Site settings

#google_analytics: UA-NNNNNNNN-N
style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

#header_pages:
#  - index.md
#  - about.md
#  - posts.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
